Jump Animations + Reorganization
Chukobyte/crescent pull request #61
Opened 2022-07-09 02:29 UTC by PineTreePizza

Added pre and post jump animations
also going up and going down on a jump animation
the up and down will be animated later on these are just the main frames to see how they look like in game
also reorganized the animation stuff every animation has its own folder now with every frame separately and every animation is now cropped to be the size of the animation

2022-07-09 09:05 UTC, PetrFlajsingr approved these changes

2022-07-09 21:44 UTC, Chukobyte requested changes
Could you rename the files and folder names lower case?  Also instead of space, use underscores.

2022-07-09 21:44 UTC, Chukobyte commented on test_games/fighter_test/assets/images/characters/mor/note.txt
> +from now on all the animations are going to be in separate folders you can remove the spritesheet animations once you implement the animations from folders in
Can you remove this file as this type of documentation isn't needed?

2022-07-10 12:32 UTC, Chukobyte approved these changes

2022-07-10 12:34 UTC, merged